---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: my-node-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
      version: blue
  template:
    metadata:
      name: my-node-app
      labels:
        app: my-node-app
        version: blue
    spec:
      containers:
      - name: my-node-app
        image: edthegreat/my-node-app
        ports:
        - containerPort: 80